### ISSUE TITLE
Add tag prompting during note creation

### ISSUE THREAD

**Issue by pdxmph** [pdxmph/notes-tui#17]
### Overview
Add the ability to prompt for tags when creating a new note, with tags being stored in the frontmatter as an array.

### Requirements
1. **Conditional feature**: Only available when `add_frontmatter` is enabled
2. **Configurable**: Add new config option `prompt_for_tags` (boolean) to enable/disable this feature
3. **User input**: After entering note title, prompt user for comma-delimited tags
4. **Storage format**: Store tags as YAML array in frontmatter (not list format)

#### 1. Config Changes
- Add `prompt_for_tags bool` to Config struct
- Update config.example.toml with new option

#### 2. Tag Input Flow
When creating a new note with both `add_frontmatter` and `prompt_for_tags` enabled:
1. User presses `n` to create new note
2. User enters title (existing behavior)
3. After title confirmation, prompt appears: "Tags (comma-separated, optional):"
4. User enters tags like: `project, meeting, important`
5. Tags are parsed and added to frontmatter

#### 3. Frontmatter Format
The tags should be stored as a YAML array:
```yaml
---
title: My Note Title
date: 2024-06-23
tags: [project, meeting, important]
---
```

Not the list format:
```yaml
# NOT THIS FORMAT
tags:
  - project
  - meeting
  - important
```

#### 4. Tag Processing
- Trim whitespace from each tag
- Handle empty input (no tags)
- Preserve tag case as entered by user
- No special character validation (allow flexibility)

### Example Configuration
```toml
# Enable frontmatter for notes
add_frontmatter = true

# Prompt for tags when creating new notes
prompt_for_tags = true
```

### UI Considerations
- Add new model state for tag input mode
- Add textinput.Model for tag input
- Update key handling for the tag input flow
- Ensure smooth transition from title → tags → editor

### Benefits
- Quick tag assignment at note creation time
- Better organization from the start
- Compatible with existing tag search functionality (`#` key)
- Maintains clean YAML array format for compatibility with other tools

**Comment by pdxmph** [comment]
I've implemented the tag prompting feature during note creation. Here's what was added:

## Implementation Details

### 1. Configuration
- Added `PromptForTags bool` field to the Config struct
- Updated `config.example.toml` with the new option and documentation
- The feature only works when `add_frontmatter = true`

### 2. User Flow
When creating a new note with both `add_frontmatter` and `prompt_for_tags` enabled:
1. User presses `n` to create new note
2. User enters title and presses Enter
3. A new prompt appears: "Tags (comma-separated, optional)..."
4. User can:
   - Enter tags like `project, meeting, important` and press Enter to create note with tags
   - Press Escape to create note without tags
   - Leave empty and press Enter to create note without tags

### 3. Tag Storage
Tags are stored in YAML array format as requested:
```yaml
---
title: My Note Title
date: 2024-06-23
tags: [project, meeting, important]
---
```

### 4. Model Changes
- Added `tagCreateMode`, `tagCreateInput`, and `pendingTitle` to the model struct
- Added proper state management for the two-step note creation process

### 5. UI Updates
- Added tag input view showing the pending title and tag input field
- Clear instructions: "[Enter] create note [Esc] create without tags"
- Proper focus management and state transitions

The feature is backward compatible - existing behavior is unchanged unless explicitly enabled in the config file.

## Testing

Create a test config with:
```toml
add_frontmatter = true
prompt_for_tags = true
```

Then create a new note with `n` and verify the tag prompting workflow.
